server:
  port: 9003
spring:
  application:
    name: sms-service
  rabbitmq:
    host: 127.0.0.1
    virtual-host: /yufan
    username: yufan
    password: 123456
    listener:
        simple:
          acknowledge-mode: manual  #手动签收
          retry:
            enabled: true  #是否支持重试
yufan:
  sms:
    accessKeyId: LTAInCic5itVRss # 你自己的accessKeyId
    accessKeySecret: KlvzUEs8mRCp6IYitDyHi0oVtMSIw # 你自己的AccessKeySecret
    signName: 天成商城 # 签名名称
    verifyCodeTemplate: SMS_151575279 # 模板名称
