server:
 port: 9008
spring:
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  application:
     name: yufan-pay-service
  datasource:
     driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://127.0.0.1:3306/springcloud?characterEncoding=utf-8
     username: root
     password: root
  jpa:
     database: MySQL
     show-sql: true
     generate-ddl: true
redis:
    pool:
      max-active: 10
    port: 6379
    host: 127.0.0.1
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10001/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /